mqtt:
  ca_cert: null
  clean_session: true
  host: 192.168.1.4
  keepalive: 60
  org: netflux
  password: diabolize_cran_epic
  port: 1883
  reconnect_timeout: 5
  use_ssl: null
  username: domosquitto
screen:
  display: :0.0
  fps: 5
  full_screen: true
  monitor:
    height: 960
    left: 0
    top: 0
    width: 1280
  monitor_number: 1
  title: dmx
  topic_base: netflux/0x435b7b2e0874eff7
  topic_subs:
  - - netflux/0x435b7b2e0874eff7/screen/#
    - 0
  uuid: '0x435b7b2e0874eff7'
server:
  host: 0.0.0.0
  port: 8080
  topic_base: netflux/0x32551e4f8cc142e3
  topic_subs:
  - - netflux/+/screen/#
    - 0
  uuid: '0x32551e4f8cc142e3'
  
